### ISSUE TITLE
Test example falls down

### ISSUE THREAD

**Issue by gerchicov-bp** [Yalantis/YALField#1]
iOS 9.1:
1. Go to pink screen
2. fill all the date except of date
3. click on date field but do nothing and press done
4. click on date field and choose any appropriate date, press done button
5. press done to pass to the next from the pink screen

Result: the app falls down

**Comment by IgorMuzyka** [comment]
Hi, by redoing steps provided by you managed to crash app with "out of bounds exception" `//shame on me for this copy/paste from stack overflow` in `YALPhoneNumberFormatter` `formattedValueFromRawValue:`.
This fail is pretty much ok because as stated in `README.md` "Formatters in Example project considered to much of a copy paste or to simple and unique case to be included in pod." so you won't have this bug when using YALField.
But, anyway will fix this. Thanks for noticing this bug.
